name: Build Exposé

on:
  push:
    paths:
      - docs/exposé/**
      - .github/workflows/exposé.yml
  workflow_dispatch:

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            # Install dependencies
            apk add python3 py3-pip python3-dev build-base gcc linux-headers
            # https://github.com/tomduck/pandoc-fignos/issues/105
            wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-linux-amd64.tar.gz && tar -xzvf pandoc-2.19.2-linux-amd64.tar.gz && mv pandoc-2.19.2/bin/* /usr/local/bin/ && rm -rf pandoc-2.19.2-linux-amd64.tar.gz pandoc-2.19.2

            cd docs/exposé

            # Install pandoc filters
            pip install -r requirements.txt

            make
      - uses: actions/upload-artifact@master
        with:
          name: exposé.pdf
          path: docs/exposé/exposé.pdf
      - run: mkdir -p build && mv docs/exposé/exposé.pdf build/
      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
