name: Build Exposé

on:
  push:
    paths:
      - docs/exposé/**
      - .github/workflows/exposé.yml
  workflow_dispatch:

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            # Install dependencies
            apk add pandoc python3 py3-pip python3-dev build-base gcc linux-headers

            cd docs/exposé

            # Install pandoc filters
            pip install -r requirements.txt

            make
      - uses: actions/upload-artifact@master
        with:
          name: exposé.pdf
          path: docs/exposé/exposé.pdf
      - run: mkdir -p build && mv docs/exposé/exposé.pdf build/
      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
